### ISSUE TITLE
Frog crash "NON printable element" / no such text 

### ISSUE THREAD

**Issue by Duchadian** [LanguageMachines/frog#43]
terminate called after throwing an instance of 'folia::NoSuchText'
  what():  no such text: NON printable element: lemma
```
Program received signal SIGABRT, Aborted.
0x00002aaaaaf24c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00002aaaaaf24c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00002aaaaaf28028 in __GI_abort () at abort.c:89
#2  0x00002aaab0b68535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00002aaab0b666d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00002aaab0b66703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00002aaab0b66922 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00002aaab05dfed6 in folia::FoliaImpl::text (this=0x2aaabd03f9b0, cls="current", retaintok=<optimized out>, strict=<optimized out>) at folia_impl.cxx:1050
#7  0x00002aaab05dab1b in folia::FoliaImpl::check_text_consistency (this=0x2aaabd03f9b0) at folia_impl.cxx:807
#8  0x00002aaab05e3371 in folia::FoliaImpl::xml (this=0x2aaabd03f9b0, recursive=<optimized out>, kanon=false) at folia_impl.cxx:917
#9  0x00002aaab05e334c in folia::FoliaImpl::xml (this=0x1b96c020, recursive=<optimized out>, kanon=false) at folia_impl.cxx:909
#10 0x00002aaab05e334c in folia::FoliaImpl::xml (this=0x1b96b860, recursive=<optimized out>, kanon=false) at folia_impl.cxx:909
#11 0x00002aaab05e334c in folia::FoliaImpl::xml (this=0x29def50, recursive=<optimized out>, kanon=false) at folia_impl.cxx:909
#12 0x00002aaab05e334c in folia::FoliaImpl::xml (this=0x1b8b6e70, recursive=<optimized out>, kanon=false) at folia_impl.cxx:909
#13 0x00002aaab0612a54 in folia::Document::to_xmlDoc (this=this@entry=0x29deb50, nsLabel=..., kanon=false) at folia_document.cxx:1693
#14 0x00002aaab0612e81 in folia::Document::toXml (this=this@entry=0x29deb50, nsLabel=..., kanon=<optimized out>) at folia_document.cxx:1701
#15 0x00002aaab06131b2 in folia::Document::save (this=this@entry=0x29deb50, os=..., nsLabel="", kanon=kanon@entry=false) at folia_document.cxx:423
#16 0x00002aaab00110f9 in save (kanon=false, os=..., this=0x29deb50) at /vol/customopt/lamachine/include/libfolia/folia_document.h:93
#17 FrogAPI::Frogtostring (this=<optimized out>,
    s=" heel goed\n !stat PDF\n [pdf] Kobus: +4-2, hooiberg: +2, tribbel: +1, jlo: -2 totaal: +3\n ja scheelt ons heel veel werk\n f00f, niet met ofzo, dat zwakth.\n !stat XML\n [XML] Kobus: +7-1,"...) at FrogAPI.cxx:1324
#18 0x00002aaaafd77865 in __pyx_pf_4frog_4Frog_2process_raw (__pyx_v_text=<optimized out>, __pyx_v_self=0x2aaaaac53418) at frog_wrapper.cpp:3643
#19 __pyx_pw_4frog_4Frog_3process_raw (__pyx_v_self=0x2aaaaac53418, __pyx_v_text=<optimized out>) at frog_wrapper.cpp:3570
#20 0x00002aaaafd746d3 in __Pyx_PyObject_CallMethO (arg=<optimized out>, func=<optimized out>) at frog_wrapper.cpp:6728
#21 __Pyx_PyObject_CallOneArg (func=<optimized out>, arg=0x29dcee0) at frog_wrapper.cpp:6759
#22 0x00002aaaafd7ad24 in __pyx_pf_4frog_4Frog_6process (__pyx_v_text=0x29dcee0, __pyx_v_self=0x2aaaaac53418) at frog_wrapper.cpp:4331
#23 __pyx_pw_4frog_4Frog_7process (__pyx_v_self=0x2aaaaac53418, __pyx_v_text=<optimized out>) at frog_wrapper.cpp:4124
#24 0x00000000004b227a in PyEval_EvalFrameEx ()
#25 0x0000000000569f94 in PyEval_EvalCode ()
#26 0x00000000004cc07c in ?? ()
#27 0x000000000047baa1 in PyRun_FileExFlags ()
#28 0x000000000047be7e in PyRun_SimpleFileExFlags ()
#29 0x00000000005bf713 in Py_Main ()
#30 0x000000000047e351 in main ()
(gdb) quit
A debugging session is active.


frog-:tokenisation took:  0 seconds, 177 milliseconds and 173 microseconds
frog-:CGN tagging took:   4 seconds, 462 milliseconds and 760 microseconds
frog-:IOB chunking took:  1 seconds, 941 milliseconds and 66 microseconds
frog-:NER took:           7 seconds, 499 milliseconds and 314 microseconds
frog-:MBMA took:          0 seconds, 172 milliseconds and 882 microseconds
frog-:Mblem took:         0 seconds, 109 milliseconds and 435 microseconds
frog-:MWU resolving took: 0 seconds, 11 milliseconds and 394 microseconds
frog-:Parsing (prepare) took: 0 seconds, 8 milliseconds and 269 microseconds
frog-:Parsing (pairs)   took: 1 seconds, 283 milliseconds and 299 microseconds
frog-:Parsing (rels)    took: 0 seconds, 73 milliseconds and 834 microseconds
frog-:Parsing (dir)     took: 0 seconds, 93 milliseconds and 892 microseconds
frog-:Parsing (csi)     took: 6 seconds, 170 milliseconds and 575 microseconds
frog-:Parsing (total)   took: 7 seconds, 648 milliseconds and 655 microseconds
frog-:Frogging in total took: 15 seconds, 437 milliseconds and 760 microseconds
frog-:problem frogging: xaf
frog-:saving to file bla failed: no such text: NON printable element: lemma
```

**Comment by kosloot** [comment]
Without the example file xaf, I can't debug

**Comment by Duchadian** [comment]
Forgot to include it, sorry!
I narrowed the problematic part down further, renamed it to probleemdeel.txt:
[probleemdeel.txt](https://github.com/LanguageMachines/frog/files/1486960/probleemdeel.txt)

**Comment by kosloot** [comment]
Well, I further narrowed it down to a file with only the word:
**current**

embarrassing

**Comment by kosloot** [comment]
I added a patch to libfolia.
That should solve it.

**Comment by kosloot** [comment]
solved
